### ISSUE TITLE
`exprots` in valid_input and first example

### ISSUE THREAD

**Issue by Pampattitude** [hola/challenge_str_search#1]
Hi,

The [valid_input.js](https://github.com/hola/challenge_substring_search/blob/master/valid_input.js) file contains an error at line two: `exports`, not `exprots`.

Also, the first example:

> `substring_search(['gsm', 'phone', 's'], '')`
> should return `{gsm: 0, phone: 0}`

doesn't seem valid, as, If I understood the problem correctly, it should return `{gsm: 0, phone: 0, s: 0}`.

**Comment by giladno** [comment]
Thank you @Pampattitude
